name = "rajt-api"
main = ".rajt/dist/index.js"
compatibility_date = "2025-12-20"

# workers_dev = false
# preview_urls = false
no_bundle = true
# send_metrics = false
compatibility_flags = [ "nodejs_compat" ]

# route = "example.com"
# route = { pattern = "api.example.com", custom_domain = true }

# [[routes]]
# pattern = "api.example.com/*"
# zone_name = "example.com"
# [[routes]]
# pattern = "api.example.com"
# custom_domain = true

# [observability]
# enabled = true
# head_sampling_rate = 0.1 # 10% of requests are logged

# PAID
# [limits]
# # The maximum CPU time allowed per invocation, in milliseconds
# cpu_ms = 100

# Bindings (KV, D1, R2..)
# kv_namespaces = []
# d1_databases = []

# [[d1_databases]]
# binding = "SCRIPT_NAME"
# database_name = "DB_NAME"
# database_id = "DB_UUID"
# preview_database_id = "PREVIEW_UUID"
# migrations_table = "MIGRATION_TABLE_NAME"
# migrations_dir = "MIGRATION_FOLDER_PATH"
# persist_to = "./.wrangler/state"

# [env.production]
# name = "rajt-api-prod"

# [vars]
# API_HOST = "api.example.com"
